spring.application.name=SwingTradingBot
server.port=8081

ibkr.host=${IBKR_HOST:127.0.0.1}
ibkr.port=${IBKR_PORT:7496}
ibkr.client-id=${IBKR_CLIENT_ID:1}
spring.mvc.async.request-timeout=75s
server.error.include-message=always
